"""added the foreign keys back

Revision ID: b29c04612fda
Revises: fde63e633c4c
Create Date: 2025-05-10 10:57:13.548277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b29c04612fda'
down_revision: Union[str, None] = 'fde63e633c4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'like_count_table', 'posts', ['post_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.create_foreign_key(None, 'likes', 'posts', ['post_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.create_foreign_key(None, 'likes', 'users', ['user_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'posts', 'users', ['owner_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.drop_constraint(None, 'like_count_table', type_='foreignkey')
    # ### end Alembic commands ###
