"""validate we are updated

Revision ID: fde63e633c4c
Revises: f30a0e10864e
Create Date: 2025-05-10 10:52:18.485024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fde63e633c4c'
down_revision: Union[str, None] = 'f30a0e10864e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('like_count_table_ibfk_1', 'like_count_table', type_='foreignkey')
    op.drop_constraint('likes_ibfk_2', 'likes', type_='foreignkey')
    op.drop_constraint('likes_ibfk_1', 'likes', type_='foreignkey')
    op.drop_constraint('posts_ibfk_1', 'posts', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('posts_ibfk_1', 'posts', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('likes_ibfk_1', 'likes', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('likes_ibfk_2', 'likes', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('like_count_table_ibfk_1', 'like_count_table', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
