"""please work

Revision ID: f30a0e10864e
Revises: 1c956e938842
Create Date: 2025-04-16 18:53:32.503077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f30a0e10864e'
down_revision: Union[str, None] = '1c956e938842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'like_count_table', 'posts', ['post_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.create_foreign_key(None, 'likes', 'users', ['user_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'likes', 'posts', ['post_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.create_foreign_key(None, 'posts', 'users', ['owner_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.drop_constraint(None, 'like_count_table', type_='foreignkey')
    # ### end Alembic commands ###
