name: Hi. This should build and deploy code

on: 
  push:
    branches:
      - main

  pull_request:

jobs:
  job1:
    runs-on: ubuntu-latest
    
    steps:
      - name: First Step - lets just print something
        run: echo "hello world"

      - name: Another step - just print another thing
        run: echo "when am i gonna print something of use?"

      - run: /bin/ls -l

      - run: pwd

      - run: git status

      - uses: actions/checkout@v2
      
      - run: cat sql_text.txt
    
      - run: git status

  job2:
    runs-on: ubuntu-latest

    steps:
      - run: echo "nameless step"

      - run: python -c "print(911)"

      - run: git status

  job3:
    runs-on: windows-latest
    
    steps:
     - run: dir /a
