name: Hi. This should build and deploy code

on: 
  push:
    branches:
      - main

  pull_request:

jobs:
  job1:

    env:
      MY_ENV : 5

    runs-on: ubuntu-latest
    
    steps:
      - name: First Step - lets just print something
        run: echo "hello world"

      - name: Another step - just print another thing
        run: echo "when am i gonna print something of use?"

      - run: touch file.txt

      - run: /bin/ls -l

      - run: pwd

      - uses: actions/checkout@v2
      
      - run: /bin/ls -l

      - run: cat sql_text.txt
    
      - run: git status

      - run: echo $MY-ENV

  job3:
    runs-on: windows-latest
    
    steps:
     - run: dir /a
