name: Hi. This should build and deploy code

on: 
  push:
    branches:
      - main

  pull_request:

jobs:
  job1:

    environment: 
      name: env123

    env:
      MY_ENV : 5
      MY_ENV2: ${{ secrets.SECRET }}


        # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    runs-on: ubuntu-latest
    
    steps:
      - name: First Step - lets just print something
        run: echo "hello world"

      - name: Another step - just print another thing
        run: echo "when am i gonna print something of use?"

      - run: touch file.txt

      - run: /bin/ls -l

      - run: pwd

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
      
      - run: /bin/ls -l

      - run: cat sql_text.txt
    
      - run: git status

      - run: echo $MY_ENV

      - run: echo ${{ secrets.SECRET }} | base64

      - run: echo $MY_ENV2

      - run: echo 123

      - run: echo ${{ secrets.S }} 

      - run: echo ${{ secrets.SECRET1 }}

      - run: echo ${{ vars.VAR }}

      - run: npm install pg

#      - run: sudo node postgres_client.js

      - run: psql -h localhost -p 5432 -U postgres -d postgres

  job3:
    runs-on: windows-latest
    
    steps:
     - run: dir /a
