name: Hi. This should build and deploy code

on: [push, pull_request ]

jobs:
  job1:
    runs-on: ubuntu-latest
    
    steps:
      name: First Step - lets just print something
      run: echo "hello world"
